# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  # username: oferusdev
 #  password: oferusdev
  username: root
  password: root
  timeout: 10000


development:
  <<: *default
host: 44.201.192.191
database: ticketsmiele
 # host: postgres_tickets


  #database: ticketsmiele
 
