# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  payments:
    juno:
      api_version: 2
      client_id: fy9cxppw4gli0hlw
      client_secret: op={[>::n^l},1v20%_pe.+&8@+8aa?p
      private_key: 89b14d6c1b0e898a7e397024cbe7b364f5bda0ebdf27aec3c88299a37d7ada9c 
      integration_url: https://sandbox.boletobancario.com/api-integration
      auth_url: https://cieloecommerce.cielo.com.br/api
    cielo:
      client_id: ef4e10fe-5551-47e5-97d1-888ce87e7892
      client_secret: hiHw9NplCsEbercrkOa1EHXGnsxQfFaIS7liaxWIMrs=
      api_url:  https://cieloecommerce.cielo.com.br/api/public 
  secret_key_base: 69131eadb6dc1192479e75d11b93907ef9acada8b86df64718e5cf42f6e6a0aeb80a45bda666251675187dabd99ba5b2f6dec8764fecd1b82c1a52dc0b5cf817
  mail_admin: no-reply@miele.cl
  pass_admin: mhydgevqregrbzrk
  webpay_wsdl:  https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/webpay_keys/public_cert_develop.crt
  webpay_client_private_key: config/webpay_keys/private_key_develop.key
  webpay_tbk_certificate: config/webpay_keys/tbk_develop.key
  webpay_commerce_code: '597020000541'
  webpay_return_url: /webpay/confirmation
  webpay_final_url: /webpay/success
  webpay_ambient: 'INTEGRACION'
  "american express":
    session_url: 'https://gateway-na.americanexpress.com/api/rest/version/59/merchant/TEST9352568548/session'
    checkout_url: 'https://gateway-na.americanexpress.com/checkout/version/59/checkout.js'
    merchant_id: 'TEST9352568548'
    auth: 'bWVyY2hhbnQuVEVTVDkzNTI1Njg1NDg6MTE2NTM3NGVmN2MwNDdhMWVjMzMzMTRhMzg3M2ExYjI='
  "visa|mastercard":
    session_url: 'https://evopaymentsmexico.gateway.mastercard.com/api/rest/version/57/merchant/TEST1031554HPP/session'
    checkout_url: 'https://evopaymentsmexico.gateway.mastercard.com/checkout/version/57/checkout.js'
    merchant_id: 'TEST1031554HPP'
    auth: 'bWVyY2hhbnQuVEVTVDEwMzE1NTRIUFA6YjdiOTVlOGM0ZmIyNGYwYmZjNjEwZWEyZDE3YmJmM2I='
  contact_emails:
    success_payment:
      mx: <%= ENV.fetch('MX_SUCCESS_PAYMENT_EMAILS', 'info@miele.com.mx') %>
      cl: <%= ENV.fetch('CL_SUCCESS_PAYMENT_EMAILS', 'info@miele.cl,patricia.anabalon@miele.com,johanna.manan@miele.com') %>
      br: <%= ENV.fetch('BR_SUCCESS_PAYMENT_EMAILS', 'info@miele.com.mx') %>
    architects: 'oferusat+arquitectos@gmail.com'
    technical-service: 'oferusat+serviciotecnico@gmail.com'
    mec-cdm: 'oferusat+meccdm@gmail.com'
    mec-gdl: 'oferusat+mecgdl@gmail.com'
  webpay:
    key_id: '597055555532'
    key_secret: '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'
  mandril_api_key: md-8t4PZQ6wxE442CtjqRHS8w
test:
  secret_key_base: 7867bea57f54607d29a441d223cb453d5702171cb3cc7a187932194c5fd357f6493f2f03bb6ca0786d2ee05e1b2932d0f2e224573e73c81b9244effdb05605f2
  mail_admin: no-reply@miele.cl
  pass_admin: mhydgevqregrbzrk
  webpay_wsdl:  https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/webpay_keys/public_cert_develop.crt
  webpay_client_private_key: config/webpay_keys/private_key_develop.key
  webpay_tbk_certificate: config/webpay_keys/tbk_develop.key
  webpay_commerce_code: '597020000541'
  webpay_return_url: /webpay/confirmation
  webpay_final_url: /webpay/success
  webpay_ambient: 'CERTIFICACION'
  contact_emails:
    success_payment:
      mx: <%= ENV.fetch('MX_SUCCESS_PAYMENT_EMAILS', 'info@miele.com.mx') %>
      cl: <%= ENV.fetch('CL_SUCCESS_PAYMENT_EMAILS', 'info@miele.cl,patricia.anabalon@miele.com,johanna.manan@miele.com') %>
      br: <%= ENV.fetch('BR_SUCCESS_PAYMENT_EMAILS', 'info@miele.com.mx') %>
    architects: 'oferusat+arquitectos@gmail.com'
    technical-service: 'oferusat+serviciotecnico@gmail.com'
    mec-cdm: 'oferusat+meccdm@gmail.com'
    mec-gdl: 'oferusat+mecgdl@gmail.com'
  webpay:
    key_id: '597055555532'
    key_secret: '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

staging: &staging
  sentry:
    dsn: https://a7eefea6734341f1b3f3ebb11234b4e5@o4504923111751680.ingest.sentry.io/4504923329265664
    environment: 'development'
  payments:
    juno:
      api_version: 2
      client_id: fY9CXpPW4GLI0hlw
      client_secret: op={[>::n^L},1V20%_pe.+&8@+8AA?P
      private_key: 89B14D6C1B0E898A7E397024CBE7B364F5BDA0EBDF27AEC3C88299A37D7ADA9C 
      integration_url: https://sandbox.boletobancario.com/api-integration
      auth_url: https://sandbox.boletobancario.com/authorization-server
    cielo:
      client_id: ef4e10fe-5551-47e5-97d1-888ce87e7892
      client_secret: hiHw9NplCsEbercrkOa1EHXGnsxQfFaIS7liaxWIMrs=
      api_url:  https://cieloecommerce.cielo.com.br/api/public 
  mail_admin: no-reply@miele.cl
  pass_admin: mhydgevqregrbzrk
  secret_key_base: 203f5ea28a1659a8c9142febd5440efaab9bd6b4e724103cddb306ffed3bd3a82091ba2f2eb09af5388ea9062ccfc48a6de0427b455fb22574195a43c5ffb635
  webpay_wsdl:  https://webpay3gint.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/webpay_keys/public_cert_develop.crt
  webpay_client_private_key: config/webpay_keys/private_key_develop.key
  webpay_tbk_certificate: config/webpay_keys/tbk_develop.key
  webpay_commerce_code: '597020000541'
  webpay_return_url: /webpay/confirmation
  webpay_final_url: /webpay/success
  webpay_ambient: 'INTEGRACION'
  "american express":
    session_url: 'https://gateway-na.americanexpress.com/api/rest/version/59/merchant/TEST9352568548/session'
    checkout_url: 'https://gateway-na.americanexpress.com/checkout/version/59/checkout.js'
    merchant_id: 'TEST9352568548'
    auth: 'bWVyY2hhbnQuVEVTVDkzNTI1Njg1NDg6MTE2NTM3NGVmN2MwNDdhMWVjMzMzMTRhMzg3M2ExYjI='
  "visa|mastercard":
    session_url: 'https://evopaymentsmexico.gateway.mastercard.com/api/rest/version/57/merchant/TEST1031554HPP/session'
    checkout_url: 'https://evopaymentsmexico.gateway.mastercard.com/checkout/version/57/checkout.js'
    merchant_id: 'TEST1031554HPP'
    auth: 'bWVyY2hhbnQuVEVTVDEwMzE1NTRIUFA6YjdiOTVlOGM0ZmIyNGYwYmZjNjEwZWEyZDE3YmJmM2I='    
  contact_emails:
    success_payment:
      mx: <%= ENV.fetch('MX_SUCCESS_PAYMENT_EMAILS', 'info@miele.com.mx') %>
      cl: <%= ENV.fetch('CL_SUCCESS_PAYMENT_EMAILS', 'info@miele.cl,patricia.anabalon@miele.com,johanna.manan@miele.com') %>
      br: <%= ENV.fetch('BR_SUCCESS_PAYMENT_EMAILS', 'info@miele.com.mx') %>
    architects: 'oferusat+arquitectos@gmail.com'
    technical-service: 'oferusat+serviciotecnico@gmail.com'
    mec-cdm: 'oferusat+meccdm@gmail.com'
    mec-gdl: 'oferusat+mecgdl@gmail.com'
  webpay:
    key_id: '597055555532'
    key_secret: '579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'

pre_production:
  <<: *staging
  site_url: 'preprod.mieletickets.garagelabs.cl'
  core:
    site_url: 'preprod.mielecore.garagelabs.cl'

production:
  payments:
    juno:
      api_version: 2
      client_id: fy9cxppw4gli0hlw
      client_secret: op={[>::n^l},1v20%_pe.+&8@+8aa?p
      private_key: 89b14d6c1b0e898a7e397024cbe7b364f5bda0ebdf27aec3c88299a37d7ada9c 
      integration_url: https://sandbox.boletobancario.com/api-integration
      auth_url: https://sandbox.boletobancario.com/authorization-server
  sentry: 
    dsn: https://b63c011e7649429fbc21a077400d19e6@o4504923111751680.ingest.sentry.io/4504996399284224
    environment: production
  mail_admin: no-reply@miele.cl
  pass_admin: mhydgevqregrbzrk
  secret_key_base: 70c415a9d1e89615efa53016a09167a26bdccff3184ef7ca02e1b65b4fa611f679da2684ce2e6689819bb7d82c7611b5cbed8b0cfa9c19988ad13b0ef99356ae
  webpay_wsdl:  https://webpay3g.transbank.cl/WSWebpayTransaction/cxf/WSWebpayService?wsdl
  webpay_client_certificate: config/webpay_keys/public_cert_production.crt
  webpay_client_private_key: config/webpay_keys/private_key_production.key
  webpay_tbk_certificate: config/webpay_keys/tbk_production.crt
  webpay_commerce_code: '597039116642'
  webpay_return_url: /webpay/confirmation
  webpay_final_url: /webpay/success
  webpay_ambient: 'PRODUCCION'
  contact_emails:
    success_payment:
      mx: <%= ENV.fetch('MX_SUCCESS_PAYMENT_EMAILS', 'info@miele.com.mx') %>
      cl: <%= ENV.fetch('CL_SUCCESS_PAYMENT_EMAILS', 'info@miele.cl,patricia.anabalon@miele.com,johanna.manan@miele.com') %>
    architects: ines.delabarra@miele.com
    technical-service: info@miele.com.mx
    mec-cdm: [angelica.montana@miele.com, polann.espinoza@miele.com]
    mec-gdl: [viviana.gonzalez-cabrera@miele.com, andres.labrada@miele.com]
  "american express":
    session_url: 'https://gateway-na.americanexpress.com/api/rest/version/59/merchant/9352568548/session'
    checkout_url: 'https://gateway-na.americanexpress.com/checkout/version/59/checkout.js'
    merchant_id: '9352568548'
    auth: 'bWVyY2hhbnQuOTM1MjU2ODU0ODo2YjBlYTBiNDliOTlhMTc1MDI4MjA5YWNjNDIxODM1NQ=='
  "visa|mastercard":
    session_url: 'https://evopaymentsmexico.gateway.mastercard.com/api/rest/version/57/merchant/1031554HPP/session'
    checkout_url: 'https://evopaymentsmexico.gateway.mastercard.com/checkout/version/57/checkout.js'
    merchant_id: '1031554HPP'
    auth: 'bWVyY2hhbnQuMTAzMTU1NEhQUDo5NTczMWIzYmU3MGRiNzliYzg0YTBiZDkzOWYwMTJhMA=='
  webpay:
    key_id: '597039116642'
    key_secret: '062837fcd1ff8da10fec236831db19f8'
  mandril_api_key: md-8t4PZQ6wxE442CtjqRHS8w

#cambiar secrets cuando suban a prod
